#!/usr/bin/env python3

"""
Command line script to send SMS messages via Twilio.

Usage:
    python send_sms.py "Your message here"
    python send_sms.py --to +15551234567 "Your message here"
    python send_sms.py --config  # Configure credentials interactively

Configuration:
    Credentials can be provided via:
    1. Environment variables: TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_FROM_NUMBER, TWILIO_TO_NUMBER
    2. .env file in the same directory
    3. Interactive configuration (stored in .env file)
"""

import argparse
import os
import sys
from pathlib import Path


def load_env_file(env_path: Path) -> dict:
    """Load environment variables from .env file"""
    config = {}
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' in line:
                    key, value = line.split('=', 1)
                    config[key.strip()] = value.strip()
    return config


def save_env_file(env_path: Path, config: dict):
    """Save configuration to .env file"""
    with open(env_path, 'w') as f:
        f.write("# Twilio SMS Configuration\n")
        f.write("# Generated by send_sms.py\n\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")


def get_credentials():
    """Get Twilio credentials from environment or .env file"""
    # Try environment variables first
    account_sid = os.getenv('TWILIO_ACCOUNT_SID')
    auth_token = os.getenv('TWILIO_AUTH_TOKEN')
    from_number = os.getenv('TWILIO_FROM_NUMBER')
    to_number = os.getenv('TWILIO_TO_NUMBER')

    # If not in environment, try .env file
    if not all([account_sid, auth_token, from_number, to_number]):
        env_path = Path(__file__).parent / '.env'
        config = load_env_file(env_path)

        account_sid = account_sid or config.get('TWILIO_ACCOUNT_SID')
        auth_token = auth_token or config.get('TWILIO_AUTH_TOKEN')
        from_number = from_number or config.get('TWILIO_FROM_NUMBER')
        to_number = to_number or config.get('TWILIO_TO_NUMBER')

    return account_sid, auth_token, from_number, to_number


def configure_credentials():
    """Interactive configuration of Twilio credentials"""
    print("Twilio SMS Configuration")
    print("=" * 60)
    print("\nYou can find these values in your Twilio Console:")
    print("https://console.twilio.com/")
    print()

    account_sid = input("TWILIO_ACCOUNT_SID: ").strip()
    auth_token = input("TWILIO_AUTH_TOKEN: ").strip()
    from_number = input("TWILIO_FROM_NUMBER (e.g., +15551234567): ").strip()
    to_number = input("TWILIO_TO_NUMBER (e.g., +15559876543): ").strip()

    if not all([account_sid, auth_token, from_number, to_number]):
        print("\nError: All fields are required!")
        return False

    # Save to .env file
    env_path = Path(__file__).parent / '.env'
    config = {
        'TWILIO_ACCOUNT_SID': account_sid,
        'TWILIO_AUTH_TOKEN': auth_token,
        'TWILIO_FROM_NUMBER': from_number,
        'TWILIO_TO_NUMBER': to_number
    }
    save_env_file(env_path, config)

    print(f"\nConfiguration saved to: {env_path}")
    print("\nTest your configuration by sending a message:")
    print('  python send_sms.py "Test message"')

    return True


def send_sms(account_sid: str, auth_token: str, from_number: str, to_number: str, message: str):
    """Send SMS message via Twilio"""
    try:
        from twilio.rest import Client
    except ImportError:
        print("Error: Twilio library not installed")
        print("Install with: pip install twilio")
        return False

    try:
        client = Client(account_sid, auth_token)

        result = client.messages.create(
            body=message,
            from_=from_number,
            to=to_number
        )

        print(f"SMS sent successfully!")
        print(f"  To: {to_number}")
        print(f"  From: {from_number}")
        print(f"  SID: {result.sid}")
        print(f"  Status: {result.status}")

        return True

    except Exception as e:
        print(f"Error sending SMS: {e}")

        # Print detailed error information if available
        if hasattr(e, 'code'):
            print(f"  Error code: {e.code}")
        if hasattr(e, 'status'):
            print(f"  HTTP status: {e.status}")
        if hasattr(e, 'msg'):
            print(f"  Message: {e.msg}")

        return False


def main():
    parser = argparse.ArgumentParser(
        description='Send SMS messages via Twilio',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Send message using default credentials
  python send_sms.py "Hello from Twilio!"

  # Send to specific number (overrides default)
  python send_sms.py --to +15551234567 "Emergency alert!"

  # Configure credentials interactively
  python send_sms.py --config

  # Show current configuration
  python send_sms.py --show-config

Environment Variables:
  TWILIO_ACCOUNT_SID   - Your Twilio Account SID
  TWILIO_AUTH_TOKEN    - Your Twilio Auth Token
  TWILIO_FROM_NUMBER   - Your Twilio phone number (e.g., +15551234567)
  TWILIO_TO_NUMBER     - Default recipient phone number (e.g., +15559876543)
        """
    )

    parser.add_argument('message', nargs='?', help='Message to send')
    parser.add_argument('--to', help='Recipient phone number (overrides default)')
    parser.add_argument('--from', dest='from_number', help='Sender phone number (overrides default)')
    parser.add_argument('--config', action='store_true', help='Configure credentials interactively')
    parser.add_argument('--show-config', action='store_true', help='Show current configuration')

    args = parser.parse_args()

    # Handle configuration mode
    if args.config:
        success = configure_credentials()
        sys.exit(0 if success else 1)

    # Get credentials
    account_sid, auth_token, from_number, to_number = get_credentials()

    # Handle show config mode
    if args.show_config:
        print("Current Twilio Configuration:")
        print("=" * 60)
        print(f"TWILIO_ACCOUNT_SID: {'*' * 20 if account_sid else 'Not set'}")
        print(f"TWILIO_AUTH_TOKEN:  {'*' * 20 if auth_token else 'Not set'}")
        print(f"TWILIO_FROM_NUMBER: {from_number or 'Not set'}")
        print(f"TWILIO_TO_NUMBER:   {to_number or 'Not set'}")
        print()
        if not all([account_sid, auth_token, from_number, to_number]):
            print("Configuration incomplete! Run with --config to set up.")
            sys.exit(1)
        sys.exit(0)

    # Validate credentials
    if not all([account_sid, auth_token, from_number]):
        print("Error: Twilio credentials not configured!")
        print("\nYou can configure them by:")
        print("  1. Running: python send_sms.py --config")
        print("  2. Setting environment variables: TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_FROM_NUMBER")
        print("  3. Creating a .env file with those variables")
        sys.exit(1)

    # Check if message provided
    if not args.message:
        parser.print_help()
        print("\nError: No message provided!")
        sys.exit(1)

    # Override to/from if provided
    if args.to:
        to_number = args.to
    if args.from_number:
        from_number = args.from_number

    # Validate to_number
    if not to_number:
        print("Error: No recipient number specified!")
        print("  Use --to +15551234567 or set TWILIO_TO_NUMBER in .env")
        sys.exit(1)

    # Send the message
    success = send_sms(account_sid, auth_token, from_number, to_number, args.message)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
